#!/usr/bin/env python3
# scripts/config/plot_config.py

PLOT_FIGURE_DPI = 300
PLOT_TITLE_FONTSIZE = 7
PLOT_AXIS_LABEL_FONTSIZE = 7
PLOT_TICK_FONTSIZE = 6
PLOT_LEGEND_FONTSIZE = 6
PLOT_LEGEND_HANDLE_LENGTH = 1.4
PLOT_LEGEND_COLUMN_SPACING = 0.8
PLOT_LEGEND_HANDLE_TEXT_PAD = 0.3
PLOT_FORMATS = ["pdf"] # "png"